/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoiib_coders;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author alext rikardo y david
 */
public class GUISpaceCenter extends javax.swing.JFrame {
    
    //Creando la ventana de validacion
    InformacionDatos VentanaDatos = new InformacionDatos(this, true);

    
    
    Estacion e1;
    Hora h1;
    Nave n1;
    DefaultTableModel modeloTabla;
    
    //Declarando la Ventana InformacionDatos
    public GUISpaceCenter() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Velocity");
        modeloTabla.addColumn("Time");      //agregar columanas con datos una vez implementada la tabla al 100%
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtRocketName = new javax.swing.JTextField();
        txtOrbitAltitude = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtSCName = new javax.swing.JTextField();
        txtSCAltitude = new javax.swing.JTextField();
        txtHeadEngineer = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tptPassWord = new javax.swing.JPasswordField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtMonth = new javax.swing.JTextField();
        txtDay = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txtHour = new javax.swing.JTextField();
        txtMinute = new javax.swing.JTextField();
        txtSecond = new javax.swing.JTextField();
        btnCleanUp = new javax.swing.JToggleButton();
        btnSave = new javax.swing.JToggleButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Space Center");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("SpaceX"));

        jLabel1.setText("Rocket Name: ");

        jLabel2.setText("Orbit Altitude: ");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Mass - Starship"));

        jLabel3.setText("Empty Mass: ");

        jLabel4.setText("Propellant Mass: ");

        jLabel5.setText("Gross Mass:");

        jLabel6.setText("120000 [kg]");

        jLabel7.setText("1320000 [kg]");

        jLabel17.setText("1199812.41 [kg]");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(46, 46, 46))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(46, 46, 46))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        txtRocketName.setText("SN-10");

        txtOrbitAltitude.setText("400");
        txtOrbitAltitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtOrbitAltitudeKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 48, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRocketName, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(txtOrbitAltitude))
                        .addGap(55, 55, 55))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtRocketName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOrbitAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Space Center"));

        jLabel8.setText("Name: ");

        jLabel9.setText("Space Center Altitude: ");

        jLabel10.setText("Head Engineer: ");

        txtSCName.setText("Kennedy");

        txtSCAltitude.setText("0");
        txtSCAltitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSCAltitudeKeyReleased(evt);
            }
        });

        jLabel18.setText("Password:");

        tptPassWord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tptPassWordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSCAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSCName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tptPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHeadEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHeadEngineer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSCName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(tptPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtSCAltitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Time Assignation"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Date"));

        jLabel11.setText("Month: ");

        jLabel12.setText("Day: ");

        jLabel13.setText("Year: ");

        txtMonth.setText("03");
        txtMonth.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMonthKeyReleased(evt);
            }
        });

        txtDay.setText("02");
        txtDay.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDayKeyReleased(evt);
            }
        });

        txtYear.setText("2021");
        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtYearKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(txtYear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtMonth))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Clock Time")));

        jLabel14.setText("Hour: ");

        jLabel15.setText("Minute: ");

        jLabel16.setText("Second: ");

        txtHour.setText("2");
        txtHour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHourKeyReleased(evt);
            }
        });

        txtMinute.setText("35");
        txtMinute.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtMinuteKeyReleased(evt);
            }
        });

        txtSecond.setText("20");
        txtSecond.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSecondKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtHour, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                    .addComponent(txtMinute)
                    .addComponent(txtSecond))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtHour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtMinute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtSecond, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnCleanUp.setText("Clean Up");

        btnSave.setText("Save");
        btnSave.setAutoscrolls(true);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCleanUp, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleanUp)
                    .addComponent(btnSave))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        // Programando el boton Save
        //InformacionDatos VentanaDatos = new InformacionDatos();
        
        //ValidacionJefe VentanaValidacion = new ValidacionJefe();
        //ValidacionJefe.tblDatos.setModel(modeloTabla);
        VentanaDatos.wKey.VentanaValidacion.tblDatos.setModel(modeloTabla);
        //Mostrando las ventanas
        //VentanaValidacion.show();
        //wKey.VentanaDatos.show();
        
        System.out.println("Mostrando la ventana datos");
        
        
        
        //Datos
        String headEngineer, passWord, nombreNave, spaceCenterDisplay, dia, mes, año;
        double v0=0;
        double dryMass=120187.59;
        double grossMass=1320000;
        double propMass=grossMass-dryMass;
        double a;                                   //variables para la tabla de datos: aceleracion momentum(implementar despues)
        double hora, min, seg, spaceCenterAltitude, orbitAltitude;
        
        
        try{
            //Integer Asignation
            dia=txtDay.getText();
            mes=txtMonth.getText();
            año=txtYear.getText();
            
            //Double Asignation
            spaceCenterAltitude=Double.parseDouble(txtSCAltitude.getText());
            orbitAltitude=Double.parseDouble(txtOrbitAltitude.getText());
            hora=Double.parseDouble(txtHour.getText());
            min=Double.parseDouble(txtMinute.getText());
            seg=Double.parseDouble(txtSecond.getText());
            
            //String Asignation
            nombreNave=txtRocketName.getText();
            headEngineer=txtHeadEngineer.getText();
            passWord=String.valueOf(tptPassWord.getPassword());
            spaceCenterDisplay=txtSCName.getText();
            
            //Creando al jefe
            VentanaDatos.wKey.jefe = new JefeEncargado(headEngineer, passWord);
            

            if(orbitAltitude>=304 && orbitAltitude<=528){
                n1=new Nave(nombreNave);  
                n1.calcularRadioOrbita();        //Distancia del centro de la tierra a la altura de orbita en kilometros         
                n1.calcularVelocidad();          //calculo de la velocidad final
                n1.calcularPerido();             //calculo del periodo
                n1.calcularTiempo();             //calculo del tiempo que demorara en entrar a orbita con la ecuacion del cohete
                
               //Compartiendo datos para busqueda
               VentanaDatos.wKey.VentanaValidacion.nave = n1;
               
                //Calculos del viaje
                n1.setVelocidad(0);
                h1 = new Hora(hora, min, seg, n1.getTiempoFinal());
                for(int t=0;t<=n1.getTiempoFinal()+1;t++){
                    if(t<n1.getTiempoFinal()){      //mientras estan prendidos los propulsores
                        v0=n1.getVelocidad();
                        grossMass=1320000-(t*(propMass/n1.getTiempoFinal()));  //el peso de la nave en cada instante dado una expulsion de combustible uniforme
                        n1.setVelocidad(3200*Math.log((grossMass+((t-1)*(propMass/n1.getTiempoFinal())))/grossMass)-(9.81));
                        a=n1.getVelocidad()-v0;
                    }
                    else{           //se apagan los propulsores
                        n1.setVelocidad(3200*Math.log((grossMass+((n1.getTiempoFinal()-1)*(propMass/n1.getTiempoFinal())))/grossMass)-(9.81));
                        a=0;
                    }
                    //tabla para llenar con los datos
                    modeloTabla.addRow(new Object[]{n1.getVelocidad(),t});
                }
                
                //visualizacion en las nuevas ventanas
                VentanaDatos.lblEngineerDisplay.setText(headEngineer);
                System.out.println("mostrando el nombre");
                VentanaDatos.wKey.VentanaValidacion.lblNameValidation.setText(headEngineer);
                VentanaDatos.wKey.lblValidateName.setText(headEngineer);
                VentanaDatos.lblSpaceCenterDisplay.setText(spaceCenterDisplay);
                VentanaDatos.lblSpaceAltitudeDisplay.setText(Double.toString(spaceCenterAltitude));
                VentanaDatos.lblrocketDisplay.setText(nombreNave);
                VentanaDatos.lblorbitalAltitudeDisplay.setText(Double.toString(orbitAltitude));
                VentanaDatos.lblfinalVelDisplay.setText(Double.toString(n1.getVelocidad()));
                VentanaDatos.lblfinalGrossDisplay.setText(Double.toString(grossMass));
                
                VentanaDatos.lblDate.setText(mes+"/"+dia+"/"+año);
                VentanaDatos.lblLaunchTime.setText(h1.establecerHora());
                VentanaDatos.lblEngineUse.setText(n1.getTiempoFinal()+" seconds");
                VentanaDatos.lblOrbitalTime.setText(h1.verificarHora());
                VentanaDatos.lblPeriod.setText(n1.getPeriodoOrbita()+" seconds");
            }
            else{
                JOptionPane.showMessageDialog(rootPane, "Debe ingresar una altitud de orbita entre [304-528] [km]");
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Debe ingresar un numero");
        } 
        
        VentanaDatos.show();
        System.out.println(VentanaDatos.wKey.jefe.getName());
        System.out.println(VentanaDatos.wKey.jefe.getNombre());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSCAltitudeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSCAltitudeKeyReleased
        try{
            if (Double.parseDouble(txtSCAltitude.getText())<0){
                txtSCAltitude.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter Space Center altitude over sea level in METERS");
            txtSCAltitude.setText(null);
        }
    }//GEN-LAST:event_txtSCAltitudeKeyReleased

    private void txtOrbitAltitudeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOrbitAltitudeKeyReleased
        try{
            if (Double.parseDouble(txtOrbitAltitude.getText())<0){
                txtOrbitAltitude.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter orbital altitude over sea level in KILOMETERS");
            txtOrbitAltitude.setText(null);
        }
    }//GEN-LAST:event_txtOrbitAltitudeKeyReleased

    private void txtMonthKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMonthKeyReleased
        try{
            if (Double.parseDouble(txtMonth.getText())>12 || Double.parseDouble(txtMonth.getText())<1){
                JOptionPane.showMessageDialog(rootPane, "Enter month [1-12]");
                txtMonth.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter month [1-12]");
            txtMonth.setText(null);
        }
        
    }//GEN-LAST:event_txtMonthKeyReleased

    private void txtDayKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDayKeyReleased
        try{
            if (Double.parseDouble(txtDay.getText())>31 || Double.parseDouble(txtDay.getText())<1){
                JOptionPane.showMessageDialog(rootPane, "Enter day [1-31]");
                txtDay.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter day [1-31]");
            txtDay.setText(null);
        }
    }//GEN-LAST:event_txtDayKeyReleased

    private void txtYearKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyReleased
        try{
            if (Double.parseDouble(txtYear.getText())<1){
                JOptionPane.showMessageDialog(rootPane, "Enter a valid year");
                txtYear.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter  valid year");
            txtYear.setText(null);
        }
    }//GEN-LAST:event_txtYearKeyReleased

    private void txtHourKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHourKeyReleased
        try{
            if (Double.parseDouble(txtHour.getText())<0 || Double.parseDouble(txtHour.getText())>23){
                JOptionPane.showMessageDialog(rootPane, "Enter an hour [0-23]");
                txtHour.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter an hour [0-23]");
            txtHour.setText(null);
        }
    }//GEN-LAST:event_txtHourKeyReleased

    private void txtMinuteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMinuteKeyReleased
        try{
            if (Double.parseDouble(txtMinute.getText())<0 || Double.parseDouble(txtMinute.getText())>59){
                JOptionPane.showMessageDialog(rootPane, "Enter a minute [0-59]");
                txtMinute.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter a minute [0-59]");
            txtMinute.setText(null);
        }
    }//GEN-LAST:event_txtMinuteKeyReleased

    private void txtSecondKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSecondKeyReleased
        try{
            if (Double.parseDouble(txtSecond.getText())<0 || Double.parseDouble(txtSecond.getText())>59){
                JOptionPane.showMessageDialog(rootPane, "Enter a second [0-59]");
                txtSecond.setText(null);
            }
        }catch(NumberFormatException nfe){
            JOptionPane.showMessageDialog(rootPane, "Enter a second [0-59]");
            txtSecond.setText(null);
        }
    }//GEN-LAST:event_txtSecondKeyReleased

    private void tptPassWordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tptPassWordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tptPassWordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUISpaceCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUISpaceCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUISpaceCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUISpaceCenter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUISpaceCenter().setVisible(true);
            }
        });
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCleanUp;
    public static javax.swing.JToggleButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private static javax.swing.JPasswordField tptPassWord;
    private javax.swing.JTextField txtDay;
    private javax.swing.JTextField txtHeadEngineer;
    private javax.swing.JTextField txtHour;
    private javax.swing.JTextField txtMinute;
    private javax.swing.JTextField txtMonth;
    private javax.swing.JTextField txtOrbitAltitude;
    private javax.swing.JTextField txtRocketName;
    private javax.swing.JTextField txtSCAltitude;
    private javax.swing.JTextField txtSCName;
    private javax.swing.JTextField txtSecond;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables
}
